import React from 'react'
import Layout from '../components/Layout'
import { container, titleContainer, title, projects, projectContainer, projectTitle, projectImageFrame, projectImageContainer, projectDescriptionContainer, projectDescription } from '../styles/portfolio.module.css'

export default function Portfolio() {
    
  // React.useEffect(() => {
  //   const scrollElements = document.querySelectorAll(".js-scroll");
  //   var throttleTimer;

  //   const throttle = (callback, time) => {
  //     if (throttleTimer) return;

  //     throttleTimer = true;
  //     setTimeout(() => {
  //       callback();
  //       throttleTimer = false;
  //     }, time);
  //   }

  //   const elementInView = (el, dividend = 1) => {
  //     const elementTop = el.getBoundingClientRect().top;

  //     return (elementTop <= (window.innerHeight || document.documentElement.clientHeight) / dividend);
  //   };

  //   const elementOutofView = (el) => {
  //     const elementTop = el.getBoundingClientRect().top;

  //     return (elementTop > (window.innerHeight || document.documentElement.clientHeight));
  //   };

  //   const displayScrollElement = (element) => {
  //     element.classList.add("scrolled");
  //   };

  //   const hideScrollElement = (element) => {
  //     element.classList.remove("scrolled");
  //   };

  //   const handleScrollAnimation = () => {
  //     scrollElements.forEach((el) => {
  //       if (elementInView(el, 1.05)) {
  //         displayScrollElement(el);
  //       } else if (elementOutofView(el)) {
  //         hideScrollElement(el)
  //       }
  //     })
  //   }

  //   window.addEventListener('scroll', () => {
  //     throttle(handleScrollAnimation, 250);
  //   })

  //   return function cleanUp() {
  //     window.removeEventListener('scroll', () => {
  //       throttle(handleScrollAnimation, 250);
  //     })
  //   }
  // }, [])


    return (
        <Layout>       
          <div className={titleContainer}>
            <h1 className={title}>Projects</h1>
          </div>      
          <div className={container}>
            <div className={projects}>
                <div className={projectContainer}>
                    <div className={projectImageFrame}>
                      <div className={projectImageContainer} />
                    </div>
                    <div className={projectDescriptionContainer}>
                      <span className={projectTitle}>Reactor</span>
                      <span className={projectDescription}>
                        This section is generated by querying the Spotify API for user’s 
                        recently played tracks, reading the context (album, playlist or artist) 
                        in which each track was played, querying the Spotify API once again for 
                        data on this particular context.   
                      </span>     
                    </div>
                </div>
                </div>
          </div>
        </Layout>
    )
}
